apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-s3
  labels:
    app: kafka-connect-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-s3
  template:
    metadata:
      labels:
        app: kafka-connect-s3
    spec:
      containers:
      - name: kafka-connect
        image: "kafka-connect:latest"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka.default.svc.cluster.local:9092"
        - name: CONNECT_GROUP_ID
          value: "kafka-connect"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "kafka-connect-config"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "kafka-connect-offset"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "kafka-connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "kafka-connect-s3"